In [139]:
import seaborn as sns
import pandas as pd
import numpy as np

In [140]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [141]:
missing_data = df.isnull()
for columns in df:
    print(missing_data[columns].value_counts())
    print(' ')

survived
False    891
Name: count, dtype: int64

pclass
False    891
Name: count, dtype: int64

sex
False    891
Name: count, dtype: int64

age
False    714
True     177
Name: count, dtype: int64

sibsp
False    891
Name: count, dtype: int64

parch
False    891
Name: count, dtype: int64

fare
False    891
Name: count, dtype: int64

embarked
False    889
True       2
Name: count, dtype: int64

class
False    891
Name: count, dtype: int64

who
False    891
Name: count, dtype: int64

adult_male
False    891
Name: count, dtype: int64

deck
True     688
False    203
Name: count, dtype: int64

embark_town
False    889
True       2
Name: count, dtype: int64

alive
False    891
Name: count, dtype: int64

alone
False    891
Name: count, dtype: int64

# Fixing Null Values

In [142]:
df["age"] = df["age"].fillna(df["age"].mean())
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

df.drop("deck", axis=1, inplace=True)

In [143]:
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [144]:
df.drop(["embark_town", "alive", "class", "who", "adult_male"], axis=1, inplace=True)
# this is because these are the data that are already in another format.

# one hot encoding

In [145]:
df["sex"] = df["sex"].map({"male": "0", "female": "1"})
df = pd.get_dummies(df, columns=["embarked"], drop_first=True )
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,alone,embarked_Q,embarked_S
0,0,3,0,22.0,1,0,7.2500,False,False,True
1,1,1,1,38.0,1,0,71.2833,False,False,False
2,1,3,1,26.0,0,0,7.9250,True,False,True
3,1,1,1,35.0,1,0,53.1000,False,False,True
4,0,3,0,35.0,0,0,8.0500,True,False,True

# Export the cleaned Dataset

In [146]:
df.to_csv("cleaned_titanic_dataset", index=False)